# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

# define a GCP VM agent to support container management (by default agent doesn't support)
agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2204

steps:
  # ------------- Build with ES released versions ---------------------
  - label: ":hammer: Build plugin with released Elasticsearch versions :elasticsearch:"
    command:
      - .buildkite/scripts/build_plugin.sh
    env:
      SNAPSHOT: false

  # ------------- Build with ES snapshot versions and main branch ---------------------
  - label: ":hammer: Build plugin with Elasticsearch snapshot versions and `main` branch :elasticsearch:"
    command:
      - .buildkite/scripts/build_plugin.sh
    env:
      SNAPSHOT: true