# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2204

steps:
  - label: ":hammer: Build plugin with LS & ES 8.x :elasticsearch:"
    # Builds with LS and ES last 8.x released version
    # Runs integration tests on 8.x released versions
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.current"
      SNAPSHOT: false
      INTEGRATION: true
      SECURE_INTEGRATION: true
      TARGET_BRANCH: "8.x"

  - label: ":hammer: Build plugin with LS 8.x-SNAPSHOT & ES `main` branch :elasticsearch:"
    # Builds with LS last 8.x released version and ES main
    # Runs integration tests on 8.x released versions
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.current"
      ELASTICSEARCH_TREEISH: "main"
      SNAPSHOT: true
      INTEGRATION: true
      SECURE_INTEGRATION: true

  - label: ":hammer: Build plugin with LS & ES `main` branch :elasticsearch:"
    # Builds with LS last 8.x released version and ES main
    # Runs integration tests on 8.x released versions
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "main"
      ELASTICSEARCH_TREEISH: "main"
      SNAPSHOT: true
      INTEGRATION: true
      SECURE_INTEGRATION: true