# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  provider: gcp
  imageProject: elastic-images-prod
  image: family/platform-ingest-logstash-multi-jdk-ubuntu-2204
  machineType: "n2-standard-4"
  diskSizeGb: 120

steps:
  # ------------- Run E2E tests ---------------------
  - label: ":test_tube: Run E2E tests with LS 8.x :rocket:"
    # uses the LS main & plugin 8.x branch when building the plugin
    # Runs integration tests against 8.x release version
    command:
      - .buildkite/scripts/run_e2e_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.current"
      TARGET_BRANCH: "8.x"

  - label: ":test_tube: Run E2E tests with LS 8.x-SNAPSHOT :rocket:"
    # uses the LS & plugin main branch when building the plugin
    # Runs integration tests against 8.x-SNAPSHOT version
    command:
      - .buildkite/scripts/run_e2e_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.current"
      SNAPSHOT: true

  - label: ":test_tube: Run E2E tests with LS `main` :rocket:"
    # uses the LS & plugin main branch when building the plugin
    # Runs integration tests against snapshot.main of https://raw.githubusercontent.com/elastic/logstash/main/ci/logstash_releases.json
    command:
      - .buildkite/scripts/run_e2e_tests.sh
    env:
      ELASTIC_STACK_VERSION: main
      SNAPSHOT: true
      ELASTICSEARCH_TREEISH: main