# define a GCP VM agent to support container management (by default agent doesn't support)
agents:
  provider: "gcp"
  machineType: "n1-standard-4"

steps:
  - label: ":hammer: CI setup and tests run on :docker:"
    command:
      # TODO: change to logstash-plugins org repo, now using personal repo to test
      - "mkdir -p .ci && curl -sL https://github.com/mashhurs/.ci/archive/main.tar.gz | tar zxvf - --skip-old-files --strip-components=1 -C .ci --wildcards '*Dockerfile*' '*docker*' '*.sh' && .ci/docker-setup.sh && ci/docker-run.sh"
    plugins:
      - docker-compose#v4.10.1:
          run: app
    env:
      ELASTIC_STACK_VERSION: "8.6.2" # TODO we need to dynamically inject the version