steps:
  - label: ":hammer: Setup .ci -> :docker: Docker setup -> :docker: Docker run"
    # TODO: change to logstash-plugins org repo, now using personal repo to test
    command:
      - "ls -a && mkdir -p .ci && curl -sL https://github.com/mashhurs/.ci/archive/main.tar.gz | tar zxvf - --strip-components=1 -C .ci --wildcards '*Dockerfile*' '*docker*' '*.sh'"
      - "ls -a && .ci/docker-setup.sh"
      - "echo Docker is running."
    env:
      ELASTIC_STACK_VERSION: "8.6.2" # TODO we need to dynamically inject the version
