steps:
  - label: ":hammer: Setup .ci"
    # TODO: change to logstash-plugins org repo, now using personal repo to test
    command: "ls -a && mkdir -p .ci && curl -sL https://github.com/mashhurs/.ci/archive/main.tar.gz | tar zxvf - --strip-components=1 -C .ci --wildcards '*Dockerfile*' '*docker*' '*.sh'"

  - wait

  - label: ":docker: Docker setup"
    command: "ls -a && .ci/docker-setup.sh"
    env:
      ELASTIC_STACK_VERSION: "8.6.2" # TODO we need to dynamically inject the version
    plugins:
      - thedyrt/skip-checkout#v0.1.1: ~ # without this, step executes new checkout and dir will be cleaned out.

  - wait

  - label: ":docker: Docker running."
    command: "echo Docker is running."
