# define a GCP VM agent to support container management (by default agent doesn't support)
agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2004

steps:
  - label: ":hammer: CI setup and tests run on :docker:"
    command:
      # TODO: change CI source after finishing test
      - "mkdir -p .ci && curl -sL https://github.com/mashhurs/.ci/archive/main.tar.gz | tar zxvf - --skip-old-files --strip-components=1 -C .ci --wildcards '*Dockerfile*' '*docker*' '*.sh' && .ci/docker-setup.sh && .ci/docker-run.sh"
    env:
      ELASTIC_STACK_VERSION: "8.6.2" # TODO we need to dynamically inject the version