# define a GCP VM agent to support container management (by default agent doesn't support)
agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2204

steps:
  # ------------- E2E tests ---------------------
  #- label: ":hammer: E2E tests run on :docker:"
  #  command:
  #    - .buildkite/scripts/e2e_tests.sh debian
  #  env:
  #    ELASTIC_STACK_VERSION: "8.x"

  # ------------- Snyk test ---------------------
  - label: ":hammer: Snyk report "
    command:
      - .buildkite/scripts/snyk/report.sh
