# define a GCP VM agent to support container management (by default agent doesn't support)
agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2204

steps:
  # ------------- Unit tests ---------------------
  - label: ":hammer: Unit tests run with LS and ES 8.x-SNAPSHOT on :docker:"
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      SNAPSHOT: true
      INTEGRATION: false

  # ------------- Integration tests ---------------------
  - label: ":hammer: Integration tests with LS and ES 8.latest run on :docker:"
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      INTEGRATION: true
      SECURE_INTEGRATION: true

  - label: ":hammer: CI setup and integration tests with LS and ES 8.x-SNAPSHOT run on :docker:"
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      SNAPSHOT: true
      LOG_LEVEL: "info"
      INTEGRATION: true
      SECURE_INTEGRATION: true
  - label: ":hammer: Integration tests with LS 8.x-SNAPSHOT and ES `main` run on :docker:"
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      ELASTICSEARCH_TREEISH: "main"
      SNAPSHOT: true
      LOG_LEVEL: "info"
      INTEGRATION: true
      SECURE_INTEGRATION: true