# define a GCP VM agent to support container management (by default agent doesn't support)
agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2204

steps:
  # ------------- Unit tests ---------------------
  - label: ":hammer: CI setup and unit tests run :docker:"
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      INTEGRATION: false
      SNAPSHOT: true

  # ------------- Integration tests ---------------------
  - label: ":hammer: CI setup and integration tests with ES 8.x run on :docker:"
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      INTEGRATION: true
      SECURE_INTEGRATION: true

  - label: ":hammer: CI setup and integration tests with ES 8.x-SNAPSHOT run on :docker:"
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      INTEGRATION: true
      LOG_LEVEL: "info"
      SECURE_INTEGRATION: true
      SNAPSHOT: true