# define a GCP VM agent to support container management (by default agent doesn't support)
agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2204

steps:
  # ------------- Unit tests ---------------------
  - label: ":hammer: Unit tests with LS & ES 8.x-SNAPSHOT :docker:"
    # Builds the plugin (with current changes) against LS 8.x-SNAPSHOT and ES version defined in gradle.properties
    # Runs unit tests on LS & ES 8.x-SNAPSHOT docker
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      SNAPSHOT: true
      INTEGRATION: false

  - label: ":hammer: Unit tests with LS 8.x-SNAPSHOT & ES main :docker:"
    # Builds the plugin (with current changes) against LS 8.x-SNAPSHOT and ES main
    # Runs unit tests on LS & ES 8.x-SNAPSHOT docker
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      ELASTICSEARCH_TREEISH: main
      INTEGRATION: false
      SNAPSHOT: true

  # ------------- Integration tests ---------------------
  - label: ":hammer: Integration tests with LS & ES 8.x :docker:"
    # Builds the plugin (with current changes) against LS 8.x and ES version defined in gradle.properties
    # Runs integration tests on LS & ES 8.x docker
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      INTEGRATION: true
      SECURE_INTEGRATION: true
      # temporary definition to cover PR-170
      # TODO: remove once 8.16 released
      ELASTICSEARCH_TREEISH: 8.16

  - label: ":hammer: Integration tests with LS & ES 8.x-SNAPSHOT :docker:"
    # Builds the plugin (with current changes) against LS 8.x-SNAPSHOT and ES version defined in gradle.properties
    # Runs integration tests on LS & ES 8.x-SNAPSHOT docker
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      SNAPSHOT: true
      INTEGRATION: true
      SECURE_INTEGRATION: true
      LOG_LEVEL: "info"

  - label: ":hammer: Integration tests with LS 8.x-SNAPSHOT & ES main :docker:"
    # Builds the plugin (with current changes) against LS 8.x-SNAPSHOT and ES main
    # Runs integration tests on LS & ES 8.x-SNAPSHOT docker
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: "8.x"
      ELASTICSEARCH_TREEISH: "main"
      SNAPSHOT: true
      INTEGRATION: true
      SECURE_INTEGRATION: true
      LOG_LEVEL: "info"

  - label: ":hammer: Integration tests with LS & ES main :docker:"
    # Builds the plugin (with current changes) against LS and ES main
    # Runs integration tests on snapshot.main of https://raw.githubusercontent.com/elastic/logstash/main/ci/logstash_releases.json
    command:
      - .buildkite/scripts/run_tests.sh
    env:
      ELASTIC_STACK_VERSION: main
      ELASTICSEARCH_TREEISH: main
      SNAPSHOT: true
      INTEGRATION: true
      SECURE_INTEGRATION: true
      LOG_LEVEL: "info"