name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue
  - type: textarea
    id: plugin-version
    attributes:
      label: Plugin Version
      description: |-
        What version of this plugin are you using?
        `bin/logstash-plugin list --verbose logstash-filter-elastic_integration`
      placeholder: e.g., logstash-filter-elastic_integration (0.1.0)
      render: shell
  - type: textarea
    id: logstash-version
    attributes:
      label: Logstash Version
      description: |-
        What version of Logstash, and in what JVM?
        `bin/logstash --version`
      placeholder: |-
        Using bundled JDK: /REDACTED/logstash-8.11.1/jdk.app/Contents/Home
        logstash 8.11.1
      render: shell
  - type: textarea
    id: java-version
    attributes:
      label: Java Version
      description: |-
        If you aren't using a bundled JDK, what specific version is the JDK being used?
        `java -version`
      placeholder: |-
        openjdk version "17.0.9" 2023-10-17
        OpenJDK Runtime Environment Homebrew (build 17.0.9+0)
        OpenJDK 64-Bit Server VM Homebrew (build 17.0.9+0, mixed mode, sharing)
      render: shell
  - type: textarea
    id: host-info
    attributes:
      label: Host Info
      description: |-
        What host and architecture?
        `uname -a`
      placeholder: |
        Darwin myhost.lan 22.6.0 Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:57 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6000 arm64
      render: shell
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true